### ISSUE TITLE
Calling ExDoc makes neovim loose the color theme

### ISSUE THREAD

**Issue by chalmagean** [slashmili/alchemist.vim#109]
Original:
![2017-08-19 at 08 11](https://user-images.githubusercontent.com/8421/29483721-282bc982-84b6-11e7-8d6f-5b7e5907e617.png)

After pressing `K`:
![2017-08-19 at 08 12](https://user-images.githubusercontent.com/8421/29483724-682c2446-84b6-11e7-96ad-4aedbf6a2792.png)

**Comment by slashmili** [comment]
@chalmagean are you using `AnsiEsc` Plugin?

**Comment by chalmagean** [comment]
I've tried that, AnsiEsc doesn't change anything.

**Comment by slashmili** [comment]
My suggestion is not to use `AnsiEsc`. That's why I'm asking :)

I just check my neovim and looks fine. I'm using [elixir-vim ver 7a0f4ec](https://github.com/elixir-editors/vim-elixir/commit/7a0f4ec19b60a1fba5ba4e5c461119d3b63fe996)

[Here](https://github.com/slashmili/alchemist.vim/blob/master/after/plugin/alchemist.vim#L125) is the place that we apply settings for opened buffer(document). Try to to disable/enable them until your main buffer doesn't lose the color

**Comment by chalmagean** [comment]
Hmm, ok so I actually had AnsiEsc installed. By removing it I now get no color changes but I do get a buffer that looks like this:

![2017-08-19 at 13 59](https://user-images.githubusercontent.com/8421/29486092-9dd17cb0-84e6-11e7-868c-cb2254d90ab3.png)

**Comment by slashmili** [comment]
@chalmagean try to kill all the `alchemist-server` process and try it again.

First time you use the plugin in a project, it checks if you have `AnsiEsc` installed, and run the server with an option that returns ansi chars. If you kill the process and run it again, it returns the docs in markdown.

**Comment by chalmagean** [comment]
Oh! You're right. It looks gorgeous now :)

Thanks.
