### ISSUE TITLE
Doesn't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by minhajuddin** [slashmili/alchemist.vim#169]
Doesn't work on Ubuntu 20.04 because of the `#!/usr/bin/env python` in `elixir_sense_client`, A workaround for this is installing the `python-is-python3` by running `sudo apt-get install python-is-python3`. There should be a better way to do it though.

**Comment by slashmili** [comment]
Hi @minhajuddin ,

Hmm `#!/usr/bin/env python` is the standard way of executing python scripts. What goes wrong when you execute the `elixir_sense_client` ?

**Comment by minhajuddin** [comment]
You are right, Ubuntu 20.04 has executables called `python2` and `python3`, that is why it fails, and installing the `python-is-python3` creates a symlink called `python` which links to `python3`. I guess the fix for this would need to intelligently find the python3 executable and test this against python3 as python2 has reached the end of life.

**Comment by slashmili** [comment]
That's strange! the idea with `#!/usr/bin/env python` that it picks up the python that you preferred as the default in your environment. Now they are making it explicit! 

Anyway It's not possible do the python search in the top of the file since it's read and executed by [execve](http://man7.org/linux/man-pages/man2/execve.2.html) and not handled by the script

I suppose the way to go is either creating symlink python to python3 or using the `python-is-python3` package

**Comment by minhajuddin** [comment]
Thanks, that makes sense. By the way, is elixir_sense supposed to work with Python3 or Python2?

**Comment by slashmili** [comment]
@minhajuddin [ElixirSense](https://github.com/elixir-lsp/elixir_sense) is purely in Elixir. `alchemist.vim` is the one which has python codes as [client](https://github.com/slashmili/alchemist.vim/blob/master/elixir_sense_client) to talk to ElixirSense server

**Comment by slashmili** [comment]
I'll close this issue. feel free to open it again if you there are some solutions.
