### ISSUE TITLE
A little slow for auto complete module methods

### ISSUE THREAD

**Issue by Cifer-Y** [slashmili/alchemist.vim#45]
I used deoplete for code complete.

When I typed `Enum.`, then the result pop up after 2 or 3 seconds.

Is that can be configed ?

Or should I config deoplete things?

**Comment by slashmili** [comment]
I'm sure @lucidstack can help here more than me :)

**Comment by Cifer-Y** [comment]
@slashmili everything is awesome today, so I will close this issue, because I think this question is not helpful for both you and me 😂

**Comment by emilsoman** [comment]
@slashmili Thanks for this great plugin! I noticed that when I add alchemist.vim to my plugins, deoplete takes a few seconds (2-3 seconds) for the autocomplete popup to be displayed in a fairly big phoenix app. Sometimes I'm only interested in autocompleting words from my current buffer and not from alchemist-server, but because of alchemist being in the loop, even words from the buffer source take 2-3 seconds. I'm wondering if there's a way to show suggestions from the buffer source immediately and delay the display of suggestions from from alchemist source until when the results are ready.
I am not sure if this is possible in deoplete at all because I have no idea how it works 😄

**Comment by slashmili** [comment]
Well not really, as you might know in order to have inside about the code there is an `alchemist-server` running in the backend and there is no way to limit it only to the current file.

I'm just wondering what part of it slow, can you follow the debugging steps from #54 and check how long does it take to get answer from each command(one from alchemist_client and another from alchemist-server directly)

**Comment by emilsoman** [comment]
@slashmili sure, I'll follow the steps and get more details on what's slow, thanks!

By the way, my question was not whether we can fetch suggestions for elixir file in current buffer, my question is something else - is it possible to make alchemist suggestions show up in the popup list in an asynchronous way so that as soon as I type something, the fastest sources are populated in the popup first ? (the variables in the current buffer, for example can be sourced by deoplete directly without asking alchemist - which can be done very fast by deoplete without waiting for alchemist).

**Comment by slashmili** [comment]
@emilsoman hmm I'm not familiar with `deoplete` so It's hard to say it's possible or not. However we can have chat on elixir slack group and see if we can do anything about that.

**Comment by emilsoman** [comment]
I enabled debug mode and give it a try. Nothing suspicious as far as I can tell. I can see two commands : `COMPX` and `COMP` for each of the characters I have typed. Anyway, to give you an idea how the slowness looks like : 

This is without alchemist:
![without-alchemist](https://cloud.githubusercontent.com/assets/1707078/18402443/00a4cb9c-76fd-11e6-801e-6aa2753853e1.gif)

This is with alchemist:
![with-alchemist](https://cloud.githubusercontent.com/assets/1707078/18402450/0f441a86-76fd-11e6-94ae-8d61be520cfa.gif)

**Comment by slashmili** [comment]
@emilsoman may I know if you experience change if the current file size(lines) is big or small?

**Comment by emilsoman** [comment]
@slashmili I can confirm that autocompletion is fast when working with a new mix project. The slowness that I observed is in an app with 155 `.ex` files. The length of the current file is not big (only around 130 lines long), but I tried with a new file to confirm - results are the same (still slow).

Looking at https://github.com/zchee/deoplete-go , it looks like they're caching results to make autocompletes faster. Do you think we can do something like that here?

**Comment by nhooyr** [comment]
@emilsoman deoplete-go doesn't cache all results. It only generates a cache for standard library completions.

**Comment by jfrolich** [comment]
Very slow for me as well in quite a big project.

**Comment by slashmili** [comment]
@jfrolich can you please create new issue and provide the information on new issue form?

This issue is quite old and a lot of thing has changed internally in this plugin.
