### ISSUE TITLE
make :Mix task detect project root?

### ISSUE THREAD

**Issue by gasparch** [slashmili/alchemist.vim#72]
it is (extremely) inconvenient that :Mix something cannot  itself find project root and execute it from top directory.

Question - I see functionality is present in python. Should I

1) write it using python integration (this requires vim compiled with python)
2) rewrite with vimscript ?
3) create separate program like 'alchemist_client' which will expose that call to vimscript?

**Comment by slashmili** [comment]
@gasparch `:Mix` is using `mix` command [directly](https://github.com/slashmili/alchemist.vim/blob/master/after/plugin/alchemist.vim#L425) 

So you need to add the logic in vimscript :)

The one that you saw and is in python is provided to `alchemist-server` which is why it was convenient to put it in python client

**Comment by gasparch** [comment]
I know that it invokes mix directly, just did not wanted to have logic duplicated in two places. 

Okay, will submit PR :)
